try
 {      }
catch [system.exception]
 {      }
finally
 {      }